language: python
python:
  - "2.7"
cache: pip
install:
  - pip install cloudpassage
script:
  - cd app/test/unit/
  - python test_config_helper.py
env:
  global:
  # halo secret
  - secure: "RZGLPgM3MuIvosOjxDKHCNQ10X67UpAQc2Oppn0weZNFgyKvlkX5k6fNWkEoHB6Zs9geWAOxWuKrWDnMqWbDUcLv+KMwC5KMqzX7k4syYk5smKmhjW/XHmqyiBVjNUtefSYf+Eg7vTWoHeV2rdozMSoRTD5gjXsgAT2pON4FI1mhJyG4bawVHXEPdQP/pr7Sqi7XlHFCkGxwZfZuFeMCQpNmnz+efAYl0x+HDp0099ybooKdo+F6un4NKqedLiPRw3WFPwQZ7NDxiNCs/w5q0Qg7PHjd/5ywXoW2MPpA7TJnyH83JKNgTFYQOeA3BwowePdeie2UuFJQ/5JbuCDMlxMEBmKMVt4/ih94UZP+5Eh9j3AArTpryFfQmuobOHGJCuVMe3ZdqpTl87Qk5uek78HQFH5aVllCXt4ZS0cpTrU4rUwnpAZBFfs/BkwKpCYG8sINX5Cldsh+TKPGrXqIQ79HJVb1qXaIkXHPiyc3i0MCosueGvEtAJNV7vai3nTYUKWcGrtEIzHNzPCJr5cDPgOtkuR5/YO8Xag0QsR4VoeVt23UqvttgTHPrf8SomFnKsC+Dy7BJenKLWE5Xdze25CxyPqm/E3wI8BitxH4TTFDsZPgx9atgqgUvzEFepVu3yK0h6zt28GW4snrBaY6fo1gwYSQLWs+OqhxRN+47T8="

