language: python
sudo: required
python:
  - "2.7"
cache: pip
install:
  - sudo apt-get install dnsutils
  - pip install cloudpassage
script:
  - git clone https://github.com/jgibbons-cp/halo_general.git
  - cd app/test/unit/
  - python test_config_helper.py
  - sed -i -e "1,/<server_group>/s/<server_group>/UnitTest/" ../../halo_api_examples/config_helper.py
  - sed -i -e "1,/<server_group_temp>/s/<server_group_temp>/UnitTestTemp/" ../../halo_api_examples/config_helper.py
  - sed -i -e "1,/<server_ip>/s/<server_ip>/54.153.14.175/" ../../halo_api_examples/config_helper.py
  - python test_server_group_methods.py
  - python test_server_methods.py
  - dig +short myip.opendns.com @resolver1.opendns.com
env:
  global:
  # halo
  - secure: "BOgUHEmdFNHMuf+kdQ+N783SyQkuIKIcgB+HxLOskCkqkuEGqZ7FFZtONMxDolVm9hk5VgrNJLAdP68OuOyrQgrc5dQHzasbOAbz7MkoAxqWmMnIOJhP2SnA5WTONXGlp9u/ES5fPPBhvxCS2q1oOpZ2YP7ZMl9AHqX7p+4OH/VoRGxrysx9h7Da6JYFIuwr+F7iDY+ImPySGtksEdaHIGiLafj0FcKfWMEYW1fDelLT9M1ZJf33RKM8fk86NKBdJQiRA0zt0ENGkUs950P2sLQsSwzpuNw5SF6f7jYXfKezf1lND4LevMi38fWqPNbc//iVu7VZoG+mj9dYnwffIpy5tLPXgLQOSoOIUkE5ivdYkl3evVKALaSqU1X+846MVP51JHZfQN5P6mLMxJQBGrdIHV+m2QXFIh7k1PtFJnpQK46dcmPQYAuDeyMGYdq7CCv9n0xW7+7cQkMKwz9anFEXqKwFggs+99y85p+o+/Og1wC7bWY+jvLJ7G/fqxPsekkN52PciG/c8n7RSY/nGWlnpnG45Oi80GeXpxvMneyWvZgETTzKRHSRd7bu+B1vNFaBB8Zx3ZudfxynG0P10zBGLfLqRVjDZ0AOSxCvJQY7QJewU85N+XerqQjZMUVYMlimoar0ikVgYpyKn0ojxWRJcKxXVVegH/dLyCQD7CI="
  # halo secret
  - secure: "RZGLPgM3MuIvosOjxDKHCNQ10X67UpAQc2Oppn0weZNFgyKvlkX5k6fNWkEoHB6Zs9geWAOxWuKrWDnMqWbDUcLv+KMwC5KMqzX7k4syYk5smKmhjW/XHmqyiBVjNUtefSYf+Eg7vTWoHeV2rdozMSoRTD5gjXsgAT2pON4FI1mhJyG4bawVHXEPdQP/pr7Sqi7XlHFCkGxwZfZuFeMCQpNmnz+efAYl0x+HDp0099ybooKdo+F6un4NKqedLiPRw3WFPwQZ7NDxiNCs/w5q0Qg7PHjd/5ywXoW2MPpA7TJnyH83JKNgTFYQOeA3BwowePdeie2UuFJQ/5JbuCDMlxMEBmKMVt4/ih94UZP+5Eh9j3AArTpryFfQmuobOHGJCuVMe3ZdqpTl87Qk5uek78HQFH5aVllCXt4ZS0cpTrU4rUwnpAZBFfs/BkwKpCYG8sINX5Cldsh+TKPGrXqIQ79HJVb1qXaIkXHPiyc3i0MCosueGvEtAJNV7vai3nTYUKWcGrtEIzHNzPCJr5cDPgOtkuR5/YO8Xag0QsR4VoeVt23UqvttgTHPrf8SomFnKsC+Dy7BJenKLWE5Xdze25CxyPqm/E3wI8BitxH4TTFDsZPgx9atgqgUvzEFepVu3yK0h6zt28GW4snrBaY6fo1gwYSQLWs+OqhxRN+47T8="

